version: '3'
services:
  # nginx:
  #   container_name: wetfoodshop_nginx
  #   image: wetfoodshop/nginx
  #   build: ./nginx
  #   ports:
  #     - "8002:80"
  #   volumes:
  #     - ./app/build/:/usr/share/nginx/html
  develop_client:
    container_name: develop_client
    image: vue/develop_client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    command:
      ['npm', 'start']
  develop_server:
    container_name: develop_server
    image: node_express/develop_server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8081"
    volumes:
      - .:/code
    depends_on:
      - develop_client
    command:
      ['npm', 'start']
  install:
    container_name: mevn_boilerplate_install
    image: mevn_boilerplate/install
    build:
      context: .
      dockerfile: Dockerfile.install
    volumes:
      - .:/code
    entrypoint:
      ['sh', 'install.sh']


