version: '3'
services:
  nginx:
    container_name: wetfoodshop_nginx
    image: wetfoodshop/nginx
    build: ./nginx
    ports:
      - "8002:80"
    volumes:
      - ./app/build/:/usr/share/nginx/html
  develop:
    container_name: wetfoodshop_app
    image: wetfoodshop/develop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command:
      ['watchify', './app/source/entry.js', '-o', './app/build/datalayer.js']
    depends_on:
      - nginx
  install:
    container_name: wetfoodshop_install
    image: wetfoodshop/install
    build:
      context: .
      dockerfile: Dockerfile.install
    volumes:
      - .:/code
    command:
      ['npm', 'install']


